### ISSUE TITLE
Questions about Analysis of Disentanglement in the paper

### ISSUE THREAD

**Issue by xiaomi4356** [SsGood/ADGCN#1]
Hi, I read your amazing work: "Adversarial Graph Disentanglement", and then I have a question about the experimental part. In the V. EXPERIMENTAL RESULTS AND ANALYSIS,  E. Analysis of Disentanglement， you compute the component confusion matrix C to illustrate the correlations among the distributions in different component spaces.
The correlation score between the i-th and j-th component distributions is given by
![image](https://user-images.githubusercontent.com/99778109/209340793-ad3c64b6-7f9e-4ac9-bde7-be934e3a6aca.png).
I don't understand why this formula is used to calculate the correlation of two vector spaces.
Why is cosine similarity calculated between every two elements in these two spaces？
Why not compute the similarity between corresponding elements as a similarity measure for two vector spaces？that is Cij=1/V*sum(hu^i*hu^j).
Finally, can you provide your code on computing the cosine similarity of two vector spaces?
I would appreciate it if you could.
Thank you!

**Comment by SsGood** [comment]
Thanks for your attention to our work and the valuable question you have raised!
I don't know if I understand this correctly, I guess the similarity you mentioned Cij=1/Vsum(hu^ihu^j) is the dot product. Actually, the dot product similarity is practically equivalent to the cosine similarity we adopt in this work, since the vector h^i_u and h^j_v are normalized during the process of micro-disentanglement.
As for the associated codes, I will release them after I have reorganized. Plz stay tuned for this project!
